"""
run_wp4_equivalence_tests.py - one command for ISSUE 10 (regression / output-equivalence).

Runs every module's equivalence checks against the integrated pipeline v4.0.0 and,
if a result folder is supplied, re-derives the published MLP metrics from the
interval-level detail. No model of the academic experiment is retrained.

    python run_wp4_equivalence_tests.py [--results <EnergyForecast_Run_... folder>]

Results are generated by the integrated pipeline; this script does not hard-code
model-performance outcomes.
"""
import subprocess
import sys

tests = [["wp4_contracts.py"], ["WP4_Ashish_MLP_Model_Integration.py"],
         ["WP4_Bishal_MLP_Validation_Evidence.py", "--self-test"],
         ["WP4_Suraj_GRU_Sequence_Engine.py"], ["WP4_Sudip_GRU_Training_Provenance.py"]]
if "--results" in sys.argv:
    res = sys.argv[sys.argv.index("--results") + 1]
    tests.append(["WP4_Bishal_MLP_Validation_Evidence.py", "--results", res, "--out",
                  "mlp_validation_evidence", "--verify-detail"])
failed = 0
for t in tests:
    print(f"\n=== {' '.join(t)} ===", flush=True)
    rc = subprocess.call([sys.executable] + t)
    failed += rc != 0
print(f"\n{len(tests) - failed}/{len(tests)} test groups passed")
print("RESULT: behaviour equivalent to v4.0.0 - existing results remain valid" if failed == 0 else
      "RESULT: a behaviour difference exists - FULL ACADEMIC RERUN REQUIRED before results are reused")
sys.exit(1 if failed else 0)
