"""
WP4_Bishal_MLP_Validation_Evidence.py

Member:              Bishal Dahal
WP4 Role:            Independent MLP validation, expanded metrics and evidence
Primary Pair:        MLP pair - Ashish Shrestha (implementation) + Bishal Dahal (independent validation)
Assigned GitHub Issue: ISSUE 02 - MLP validation and evidence framework
                     (also supports ISSUE 07 neural-vs-previous and ISSUE 10 regression tests)
Integration Target:  Energy_Demand_Forecasting_Pipeline.py v4.0.0
                     Sections J (metrics), U-X (lead time, peak, stability, DM),
                     Y (figure N01) and the MLP rows of the Section Z exports.
Purpose:             Validate the MLP independently of the person who built it, using
                     ONLY the files the integrated pipeline wrote: learning curves,
                     MAE/RMSE/sMAPE/nMAE/Bias/MASE/R2, residuals, peaks, historical-year
                     stability, lead-time bands and the comparison with the strongest
                     previous model. It re-derives numbers from the interval-level
                     detail where possible and reports any disagreement.

Provenance: role-aligned WP4 collaboration artefact prepared from the team's
integrated implementation for genuine branch-based review and merging. It reads
outputs; it never retrains a model.

Results are generated by the integrated pipeline; this module does not hard-code
model-performance outcomes.

Usage
    python WP4_Bishal_MLP_Validation_Evidence.py --self-test
    python WP4_Bishal_MLP_Validation_Evidence.py --results <run folder> --out <folder> [--verify-detail]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd

from wp4_contracts import MetricResult, TrainingHistory, load_pipeline

edp = load_pipeline()
MODEL = "MLP"
OK = ("MODEL_READY", "MODEL_READY_WITH_WARNING")


# ---------------------------------------------------------------------------
# 1. Loading the evidence package
# ---------------------------------------------------------------------------

REQUIRED = {
    "by_year": "metrics/model_comparison_by_year.csv",
    "by_region": "metrics/model_comparison_by_region.csv",
    "by_horizon": "metrics/model_comparison_by_horizon.csv",
    "stability": "metrics/model_stability.csv",
    "peak": "metrics/peak_demand_metrics.csv",
    "residual": "metrics/residual_analysis.csv",
    "neural_vs_previous": "metrics/neural_vs_previous_comparison.csv",
    "history": "metrics/neural_training_history.csv",
}


def load_results(results_dir: str | Path) -> dict[str, pd.DataFrame]:
    """Load the CSVs this validation needs; a missing file is an explicit error."""
    root = Path(results_dir)
    out, missing = {}, []
    for key, rel in REQUIRED.items():
        p = root / rel
        if p.exists():
            out[key] = pd.read_csv(p)
        else:
            missing.append(rel)
    if missing:
        raise FileNotFoundError(f"evidence files missing: {missing}")
    return out


# ---------------------------------------------------------------------------
# 2. Learning-curve validation
# ---------------------------------------------------------------------------

def learning_curve_summary(history: pd.DataFrame, model: str = MODEL,
                           epoch_limit: int | None = None) -> pd.DataFrame:
    """One row per region x origin for the early-stopping fit.

    Classification rules (declared, not tuned to the result):
      EPOCH_LIMIT_REACHED - best epoch == last epoch == configured limit (may be under-trained)
      OVERFITTING_SIGNAL  - final val loss > 1.10 x best val loss while train loss fell
      CONVERGED           - otherwise (early stopping ended the fit near a minimum)
    """
    params = edp.MLP_PARAMETERS["full"] if model == "MLP" else edp.GRU_PARAMETERS["full"]
    limit = epoch_limit or params["epochs"]
    h = history[(history["model"] == model) & (history["phase"] == "early_stopping_fit")]
    rows = []
    for (region, origin), g in h.groupby(["region", "backtest_origin"]):
        g = g.sort_values("epoch")
        TrainingHistory(region, model, pd.Timestamp(origin), g).validate()
        ib = g["val_loss"].idxmin()
        best_ep, last_ep = int(g.loc[ib, "epoch"]), int(g["epoch"].max())
        min_val, final_val = float(g.loc[ib, "val_loss"]), float(g["val_loss"].iloc[-1])
        train_best, train_final = float(g.loc[ib, "loss"]), float(g["loss"].iloc[-1])
        if best_ep == last_ep == limit:
            verdict = "EPOCH_LIMIT_REACHED"
        elif final_val > 1.10 * min_val and train_final < train_best:
            verdict = "OVERFITTING_SIGNAL"
        else:
            verdict = "CONVERGED"
        rows.append({"region": region, "model": model, "backtest_origin": origin,
                     "epochs_run": last_ep, "best_epoch": best_ep, "min_val_loss": min_val,
                     "train_loss_at_best": train_best, "generalisation_gap": min_val - train_best,
                     "final_val_loss": final_val, "final_learning_rate": float(g["learning_rate"].iloc[-1]),
                     "verdict": verdict})
    return pd.DataFrame(rows)


def plot_learning_curves(history: pd.DataFrame, out_png: Path, model: str = MODEL) -> Path:
    """Re-draw N01 from neural_training_history.csv (independent of the pipeline plot code)."""
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    h = history[(history["model"] == model) & (history["phase"] == "early_stopping_fit")]
    regions = sorted(h["region"].unique())
    fig, axes = plt.subplots(2, 3, figsize=(14, 7), squeeze=False)
    for ax, r in zip(axes.ravel(), regions):
        g = h[h["region"] == r]
        for i, (o, go) in enumerate(g.groupby("backtest_origin")):
            c = plt.cm.viridis(i / max(1, g["backtest_origin"].nunique() - 1))
            ax.plot(go["epoch"], go["loss"], color=c, lw=1, label=f"{str(o)[:4]} train")
            ax.plot(go["epoch"], go["val_loss"], color=c, lw=1, ls="--", label=f"{str(o)[:4]} val")
        ax.set_title(r); ax.set_xlabel("epoch"); ax.set_ylabel("Huber loss (scaled)")
    for ax in axes.ravel()[len(regions):]:
        ax.axis("off")
    axes[0, 0].legend(fontsize=6, ncol=2)
    fig.suptitle(f"{model} - training vs validation loss (independent re-plot)")
    fig.tight_layout()
    out_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_png, dpi=140)
    plt.close(fig)
    return out_png


# ---------------------------------------------------------------------------
# 3. Metric re-derivation (equivalence against the published tables)
# ---------------------------------------------------------------------------

def recompute_from_detail(detail: pd.DataFrame, model: str = MODEL) -> pd.DataFrame:
    """Recompute region x origin metrics from all_models_backtest_detail with the
    pipeline's own group_metrics(), for comparison with model_comparison_by_year."""
    d = detail[detail["model"] == model]
    return edp.group_metrics(d, ["region", "model", "backtest_year"])


def compare_with_published(recomputed: pd.DataFrame, by_year: pd.DataFrame,
                           cols=("MAE", "RMSE", "nMAE_pct", "Bias")) -> pd.DataFrame:
    pub = by_year[by_year["status"].isin(OK)]
    j = recomputed.merge(pub, on=["region", "model", "backtest_year"], suffixes=("_recomputed", "_published"))
    for c in cols:
        j[f"{c}_abs_diff"] = (j[f"{c}_recomputed"] - j[f"{c}_published"]).abs()
    return j[["region", "model", "backtest_year"] + [f"{c}_abs_diff" for c in cols]]


# ---------------------------------------------------------------------------
# 4. MLP evidence tables
# ---------------------------------------------------------------------------

def mlp_year_table(by_year: pd.DataFrame, nvp: pd.DataFrame) -> pd.DataFrame:
    """MLP vs the strongest previous model of each region, per backtest year."""
    prev = nvp.set_index("region")["strongest_previous_model"]
    rows = []
    for region, champ in prev.items():
        s = by_year[(by_year["region"] == region) & by_year["status"].isin(OK)]
        a = s[s["model"] == MODEL].set_index("backtest_year")
        b = s[s["model"] == champ].set_index("backtest_year")
        for yr in sorted(set(a.index) & set(b.index)):
            rows.append({"region": region, "backtest_year": yr, "origin_type": a.loc[yr, "origin_type"],
                         "used_for_selection": bool(a.loc[yr, "used_for_selection"]),
                         "previous_champion": champ, "MLP_MAE": a.loc[yr, "MAE"],
                         "champion_MAE": b.loc[yr, "MAE"],
                         "MLP_change_pct": 100 * (a.loc[yr, "MAE"] - b.loc[yr, "MAE"]) / b.loc[yr, "MAE"],
                         "MLP_better": bool(a.loc[yr, "MAE"] < b.loc[yr, "MAE"])})
    return pd.DataFrame(rows)


def mlp_horizon_table(by_horizon: pd.DataFrame, nvp: pd.DataFrame) -> pd.DataFrame:
    h = by_horizon[by_horizon["origin_scope"] == "SELECTION_MEAN"]
    prev = nvp.set_index("region")["strongest_previous_model"]
    rows = []
    for region, champ in prev.items():
        for band in ["Days 1-7", "Days 8-30", "Months 2-4", "Full horizon"]:
            m = h[(h["region"] == region) & (h["model"] == MODEL) & (h["lead_band"] == band)]
            c = h[(h["region"] == region) & (h["model"] == champ) & (h["lead_band"] == band)]
            if len(m) and len(c):
                rows.append({"region": region, "lead_band": band, "MLP_nMAE_pct": m["nMAE_pct"].iloc[0],
                             "champion": champ, "champion_nMAE_pct": c["nMAE_pct"].iloc[0],
                             "MLP_MAE_change_pct": 100 * (m["MAE"].iloc[0] - c["MAE"].iloc[0]) / c["MAE"].iloc[0]})
    return pd.DataFrame(rows)


def mlp_peak_table(peak: pd.DataFrame) -> pd.DataFrame:
    p = peak[peak["used_for_selection"] & peak["model"].isin([MODEL, "RandomForest_A", "RandomForest_B"])]
    cols = [c for c in ["peak_MAE", "peak_RMSE", "peak_Bias", "daily_peak_MAE", "daily_peak_Bias",
                        "peak_day_precision", "peak_day_recall", "peak_day_F1"] if c in p.columns]
    return p.groupby(["region", "model"])[cols].mean().reset_index()


def mlp_residual_table(residual: pd.DataFrame) -> pd.DataFrame:
    r = residual[residual["model"] == MODEL]
    out = []
    for (region, dim), g in r.groupby(["region", "dimension"]):
        worst = g.loc[g["MAE"].idxmax()]
        out.append({"region": region, "dimension": dim, "worst_value": worst["value"], "worst_MAE": worst["MAE"],
                    "mean_residual_range_MW": f"{g['mean_residual_MW'].min():.0f} .. {g['mean_residual_MW'].max():.0f}"})
    return pd.DataFrame(out)


def mlp_stability_table(stability: pd.DataFrame) -> pd.DataFrame:
    cols = [c for c in ["region", "model", "mean_MAE", "std_origin_MAE", "worst_origin_year",
                        "worst_origin_MAE", "origin_wins", "horizon_degradation_ratio"] if c in stability]
    return stability[stability["model"].isin([MODEL, "RandomForest_A", "RandomForest_B"])][cols]


def evidence_summary_markdown(curves: pd.DataFrame, years: pd.DataFrame, nvp: pd.DataFrame) -> str:
    """Plain-English summary generated from the tables (no numbers typed by hand)."""
    lines = ["# MLP independent validation summary", ""]
    if len(curves):
        vc = curves["verdict"].value_counts().to_dict()
        lines.append(f"- Learning curves: {len(curves)} early-stopping fits; verdicts {vc}; "
                     f"median best epoch {curves['best_epoch'].median():.0f}; "
                     f"mean generalisation gap {curves['generalisation_gap'].mean():.4f} (scaled Huber).")
    sel = years[years["used_for_selection"]]
    if len(sel):
        lines.append(f"- Selection origins: MLP beat the previous regional champion in "
                     f"{int(sel['MLP_better'].sum())} of {len(sel)} region-years.")
    lim = years[~years["used_for_selection"]]
    if len(lim):
        lines.append(f"- 2022 limited-history warm-up: MLP beat the champion in {int(lim['MLP_better'].sum())} of "
                     f"{len(lim)} regions (reported, not used for selection).")
    if "MLP_MAE_change_vs_previous_pct" in nvp:
        lines.append(f"- Mean MAE change vs strongest previous model across regions: "
                     f"{nvp['MLP_MAE_change_vs_previous_pct'].mean():+.2f}% (negative = MLP better); "
                     f"material improvements: {int(nvp['MLP_material_improvement'].sum())}.")
    return "\n".join(lines) + "\n"


def export_mlp_evidence(results_dir: str | Path, out_dir: str | Path, verify_detail: bool = False) -> dict:
    res = load_results(results_dir)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    tables = {
        "mlp_learning_curve_summary": learning_curve_summary(res["history"]),
        "mlp_vs_champion_by_year": mlp_year_table(res["by_year"], res["neural_vs_previous"]),
        "mlp_vs_champion_by_horizon": mlp_horizon_table(res["by_horizon"], res["neural_vs_previous"]),
        "mlp_peak_comparison": mlp_peak_table(res["peak"]),
        "mlp_residual_summary": mlp_residual_table(res["residual"]),
        "mlp_stability": mlp_stability_table(res["stability"]),
    }
    if verify_detail:
        det = pd.read_csv(Path(results_dir) / "forecasts" / "all_models_backtest_detail.csv.gz",
                          usecols=["region", "model", "backtest_year", "actual_MW", "forecast_MW"])
        tables["mlp_metric_equivalence"] = compare_with_published(recompute_from_detail(det), res["by_year"])
    for name, df in tables.items():
        df.to_csv(out / f"{name}.csv", index=False)
    plot_learning_curves(res["history"], out / "N01_MLP_learning_curves_independent.png")
    (out / "MLP_VALIDATION_SUMMARY.md").write_text(
        evidence_summary_markdown(tables["mlp_learning_curve_summary"], tables["mlp_vs_champion_by_year"],
                                  res["neural_vs_previous"]), encoding="utf-8")
    return tables


# ---------------------------------------------------------------------------
# 5. Self-test (synthetic; checks the metric definitions against the pipeline)
# ---------------------------------------------------------------------------

def self_test() -> int:
    ok = True
    rng = np.random.default_rng(3)
    a = rng.normal(1000, 100, 500)
    f = a + rng.normal(0, 20, 500)
    m = MetricResult.compute("SA1", MODEL, "full", a, f, edp).values
    manual_mae = float(np.mean(np.abs(f - a)))
    ok &= abs(m["MAE"] - manual_mae) < 1e-9
    ok &= abs(m["nMAE_pct"] - 100 * manual_mae / a.mean()) < 1e-9
    ok &= abs(m["Bias"] - float(np.mean(f - a))) < 1e-9
    det = pd.DataFrame({"region": "SA1", "model": MODEL, "backtest_year": 2025, "actual_MW": a, "forecast_MW": f})
    g = recompute_from_detail(det)
    ok &= abs(g["MAE"].iloc[0] - m["MAE"]) < 1e-9
    hist = pd.DataFrame({"model": MODEL, "phase": "early_stopping_fit", "region": "SA1",
                         "backtest_origin": "2025-09-01", "epoch": np.arange(1, 11),
                         "loss": np.linspace(1, .1, 10), "val_loss": [.9, .6, .4, .3, .25, .26, .28, .3, .33, .36],
                         "learning_rate": 1e-3})
    s = learning_curve_summary(hist)
    ok &= s["best_epoch"].iloc[0] == 5 and s["verdict"].iloc[0] == "OVERFITTING_SIGNAL"
    print(f"MLP validation self-test: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--results")
    ap.add_argument("--out", default="mlp_validation_evidence")
    ap.add_argument("--verify-detail", action="store_true")
    a = ap.parse_args()
    if a.self_test or not a.results:
        return self_test()
    tables = export_mlp_evidence(a.results, a.out, a.verify_detail)
    for k, v in tables.items():
        print(f"  wrote {k}.csv ({len(v)} rows)")
    if "mlp_metric_equivalence" in tables:
        e = tables["mlp_metric_equivalence"]
        worst = e[[c for c in e.columns if c.endswith("_abs_diff")]].max().max()
        print(f"  detail-vs-published max abs difference: {worst:.6f}")
        return 0 if worst < 1e-3 else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
