"""
WP4_Ashish_MLP_Model_Integration.py

Member:              Ashish Shrestha
WP4 Role:            MLP model implementation and overall model-selection integration
Primary Pair:        MLP pair - Ashish Shrestha (implementation) + Bishal Dahal (independent validation)
Assigned GitHub Issue: ISSUE 01 - MLP model architecture and integration
Integration Target:  Energy_Demand_Forecasting_Pipeline.py v4.0.0
                     Section P (neural preprocessing) and Section Q (MLP), plus the
                     "MLP" branch of run_model() in Section T.
Purpose:             Isolate the MLP so it can be reviewed, tested and merged on its
                     own branch: configuration, architecture, Huber loss, the Feature
                     Set B neural contract, training-only scaling, the chronological
                     validation split, fit/predict, recursive integration through the
                     pipeline's run_ml(), the registry hook and the prediction contract.

Provenance: this is a role-aligned WP4 collaboration artefact prepared from the
team's integrated implementation for genuine branch-based review and merging.
The integrated pipeline (v4.0.0) produced the WP4 results and remains the source
of truth; equivalence_checks() must pass before this module may replace Section Q.

Results are generated by the integrated pipeline; this module does not hard-code
model-performance outcomes.
"""
from __future__ import annotations

import copy
import sys
import time

import numpy as np
import pandas as pd

from wp4_contracts import (ForecastResult, ModelInputContract, NeuralScalerBundle,
                           check_constants, load_pipeline)

MODEL_NAME = "MLP"
edp = load_pipeline()


# ---------------------------------------------------------------------------
# 1. Configuration and input contract
# ---------------------------------------------------------------------------

def mlp_parameters(quick: bool = False) -> dict:
    """A copy of the pipeline's MLP_PARAMETERS (never a second definition)."""
    return copy.deepcopy(edp.MLP_PARAMETERS["quick" if quick else "full"])


def mlp_input_contract() -> ModelInputContract:
    """Feature Set B minus the three trend columns, in the pipeline's order.

    Trend columns are withheld because a neural network extrapolates them linearly
    beyond the training range, whereas trees plateau (see NN_EXCLUDED_FEATURES)."""
    return ModelInputContract(model_name=MODEL_NAME, feature_set_label="B_nn",
                              feature_names=tuple(edp.FEATURE_SET_B_NN),
                              requires_tensorflow=True,
                              excluded_features=tuple(edp.NN_EXCLUDED_FEATURES))


def registry_entry() -> dict:
    """Registry hook: the metadata the pipeline stores for the MLP."""
    return dict(edp.MODEL_REGISTRY[MODEL_NAME])


# ---------------------------------------------------------------------------
# 2. Architecture
# ---------------------------------------------------------------------------

def build_mlp_network(tf, n_inputs: int, params: dict):
    """Input -> [Dense -> (BatchNorm) -> ReLU -> Dropout] x len(hidden) -> Dense(1, linear).

    Loss is Huber(delta=HUBER_DELTA) on the z-scored target: quadratic near zero,
    linear for large misses - close to the MAE the project is judged on."""
    L = tf.keras.layers
    reg = tf.keras.regularizers.l2(params["l2"]) if params["l2"] else None
    inp = tf.keras.Input(shape=(n_inputs,), name="engineered_features")
    h = inp
    for units, drop in zip(params["hidden_units"], params["dropout"]):
        h = L.Dense(units, kernel_regularizer=reg)(h)
        if params["batch_norm"]:
            h = L.BatchNormalization()(h)
        h = L.Activation("relu")(h)
        if drop:
            h = L.Dropout(drop)(h)
    out = L.Dense(1, activation="linear", name="demand_scaled")(h)
    net = tf.keras.Model(inp, out, name="MLP_regressor")
    net.compile(optimizer=tf.keras.optimizers.Adam(params["learning_rate"]),
                loss=tf.keras.losses.Huber(delta=edp.HUBER_DELTA), metrics=["mae"])
    return net


# ---------------------------------------------------------------------------
# 3. Training-only scaling and chronological validation
# ---------------------------------------------------------------------------

def chronological_validation_mask(idx: pd.DatetimeIndex, origin: pd.Timestamp) -> np.ndarray:
    """True for the last NEURAL_VALIDATION_DAYS before the origin (pipeline rule)."""
    return edp._validation_split(pd.DatetimeIndex(idx), pd.Timestamp(origin))


def fit_scalers(X: np.ndarray, y: np.ndarray, idx: pd.DatetimeIndex, rows: np.ndarray,
                features: list) -> NeuralScalerBundle:
    """Fit feature + target scalers on the selected TRAINING rows only."""
    fs = edp.ColumnScaler(features).fit(X[rows])
    ts = edp.TargetScaler().fit(y[rows])
    idx = pd.DatetimeIndex(idx)
    return NeuralScalerBundle(fs, ts, fitted_until=idx[rows].max() if rows.any() else None,
                              fitted_rows=int(rows.sum()))


# ---------------------------------------------------------------------------
# 4. Learner (fit / predict) - the object run_ml() drives recursively
# ---------------------------------------------------------------------------

class WP4MLPForecaster:
    """Same algorithm as pipeline.MLPLearner, written against the shared contract.

    fit():   scalers on pre-validation rows -> early-stopped fit on the 8-week
             chronological validation block -> (full mode) refit on every
             pre-origin row for the best epoch count, replaying the LR path.
    predict(): scale with the fitted bundle, predict, inverse-transform to MW.
    """

    def __init__(self, quick: bool, seed: int, label: str):
        self.p = mlp_parameters(quick)
        self.quick, self.seed, self.label = quick, seed, label
        self.contract = mlp_input_contract()
        self.net = None
        self.scalers: NeuralScalerBundle | None = None
        self.features: list = []
        self.history: pd.DataFrame | None = None
        self.best_epoch: int | None = None
        self.origin: pd.Timestamp | None = None

    # the pipeline's run_ml() calls fit(X, y, idx, origin)
    def fit(self, X: pd.DataFrame, y: np.ndarray, idx, origin, tag: str = "") -> None:
        tf = edp.get_tf()
        self.contract.validate_frame(X)
        self.features, self.origin = list(X.columns), pd.Timestamp(origin)
        Xv = X.to_numpy(dtype=float)
        is_val = chronological_validation_mask(idx, origin)
        tr = ~is_val
        self.scalers = fit_scalers(Xv, y, idx, tr, self.features)
        self.scalers.assert_before(self.origin)
        fs, ts = self.scalers.feature_scaler, self.scalers.target_scaler

        tf.keras.backend.clear_session()
        edp.set_global_seeds(self.seed)
        net = build_mlp_network(tf, Xv.shape[1], self.p)
        cbs, rec = edp._keras_callbacks(tf, self.p, self.label, with_validation=True)
        net.fit(fs.transform(Xv[tr]), ts.transform(y[tr]),
                validation_data=(fs.transform(Xv[is_val]), ts.transform(y[is_val])),
                epochs=self.p["epochs"], batch_size=self.p["batch_size"], shuffle=True,
                verbose=0, callbacks=cbs)
        edp.check_cancel()
        hist = edp._history_frame(rec, "early_stopping_fit")
        self.best_epoch, lr_path = edp._best_epoch(rec)

        if edp.NEURAL_REFIT_ON_FULL_HISTORY and not self.quick:
            all_rows = np.ones(len(Xv), bool)
            self.scalers = fit_scalers(Xv, y, idx, all_rows, self.features)
            self.scalers.assert_before(self.origin)
            fs, ts = self.scalers.feature_scaler, self.scalers.target_scaler
            tf.keras.backend.clear_session()
            edp.set_global_seeds(self.seed)
            net = build_mlp_network(tf, Xv.shape[1], self.p)
            cbs2, rec2 = edp._keras_callbacks(tf, self.p, self.label + " refit",
                                              with_validation=False, lr_replay=lr_path)
            net.fit(fs.transform(Xv), ts.transform(y), epochs=max(1, self.best_epoch),
                    batch_size=self.p["batch_size"], shuffle=True, verbose=0, callbacks=cbs2)
            edp.check_cancel()
            hist = pd.concat([hist, edp._history_frame(rec2, "refit_full_history")], ignore_index=True)
        self.net, self.history = net, hist

    def predict(self, X: pd.DataFrame) -> np.ndarray:
        """Prediction contract: one MW value per row, same order as X."""
        Z = self.scalers.feature_scaler.transform(X[self.features].to_numpy(dtype=float))
        z = np.asarray(self.net.predict_on_batch(Z)).reshape(-1)
        return self.scalers.target_scaler.inverse(z)

    def architecture(self) -> dict:
        return {"type": MODEL_NAME, "inputs": len(self.features), **self.p,
                "loss": f"Huber(delta={edp.HUBER_DELTA})", "optimizer": "Adam",
                "best_epoch": self.best_epoch,
                "refit_on_full_history": bool(edp.NEURAL_REFIT_ON_FULL_HISTORY and not self.quick)}


# ---------------------------------------------------------------------------
# 5. Recursive forecast integration (uses the pipeline engine, not a copy)
# ---------------------------------------------------------------------------

def run_mlp_backtest(panel, maps, region: str, quick: bool = False,
                     max_train_rows: int | None = None) -> ForecastResult:
    """Train on pre-origin rows and forecast the whole horizon in 48-interval day blocks
    through pipeline.run_ml() - the same recursion, feature rebuild and median-fill
    rule used for RandomForest/XGBoost, so the comparison stays like-for-like."""
    seed = edp.stable_seed(region, MODEL_NAME, maps.origin)
    learner = WP4MLPForecaster(quick, seed, f"{region} MLP {maps.origin.date()}")
    try:
        run = edp.run_ml(panel, MODEL_NAME, list(edp.FEATURE_SET_B_NN), maps, learner, max_train_rows)
    except edp.DependencyMissing as exc:
        run = edp.Run(name=MODEL_NAME, status="NOT_RUN", detail=f"NOT RUN - {exc}. Not substituted.")
    run.extra["best_epoch"] = learner.best_epoch
    result = ForecastResult.from_run(run, region, maps.origin)
    result.validate(len(panel.grid_pos))
    return result


# ---------------------------------------------------------------------------
# 6. Equivalence checks (no retraining of the academic experiment)
# ---------------------------------------------------------------------------

def equivalence_checks(run_tf: bool = True) -> list[tuple[str, bool]]:
    """Prove this module reproduces the pipeline behaviour that generated the results."""
    checks = [
        ("contract constants match pipeline", not check_constants(edp)),
        ("full MLP parameters equal pipeline", mlp_parameters(False) == edp.MLP_PARAMETERS["full"]),
        ("quick MLP parameters equal pipeline", mlp_parameters(True) == edp.MLP_PARAMETERS["quick"]),
        ("MLP feature list equals FEATURE_SET_B_NN (order included)",
         list(mlp_input_contract().feature_names) == list(edp.FEATURE_SET_B_NN)),
        ("trend columns excluded", not set(edp.NN_EXCLUDED_FEATURES) & set(mlp_input_contract().feature_names)),
        ("registry entry unchanged", registry_entry() == edp.MODEL_REGISTRY[MODEL_NAME]),
    ]
    rng = np.random.default_rng(7)
    idx = pd.date_range("2024-01-01", periods=96 * 90, freq="30min")
    origin = idx[-1] + pd.Timedelta(minutes=30)
    mask = chronological_validation_mask(idx, origin)
    checks.append(("validation block = last 56 days before origin",
                   bool(mask.sum() == 56 * 48 and idx[mask].min() == origin - pd.Timedelta(days=56))))
    X = rng.normal(size=(len(idx), 4))
    X[5, 2] = np.nan
    y = rng.normal(1000, 50, len(idx))
    b = fit_scalers(X, y, idx, ~mask, ["a", "b", "c", "d"])
    ref = edp.ColumnScaler(["a", "b", "c", "d"]).fit(X[~mask])
    checks.append(("scaler fitted on training rows only (matches pipeline)",
                   np.allclose(b.feature_scaler.transform(X), ref.transform(X)) and b.fitted_until < origin))
    if run_tf and edp.tf_status()["available"]:
        tf = edp.get_tf()
        for mode in ("full", "quick"):
            p = edp.MLP_PARAMETERS[mode]
            ref_net = edp.MLPLearner(mode == "quick", 1, "ref")._build(tf, 51)
            new_net = build_mlp_network(tf, 51, p)
            checks.append((f"{mode} architecture parameter count equals pipeline",
                           ref_net.count_params() == new_net.count_params()))
        # identical predictions from identical seeds on a tiny synthetic fit
        n = 48 * 120
        tidx = pd.date_range("2024-01-01", periods=n, freq="30min")
        feats = list(edp.FEATURE_SET_B_NN)
        Xs = pd.DataFrame(rng.normal(size=(n, len(feats))), columns=feats, index=tidx)
        ys = 1000 + 50 * Xs.iloc[:, 0].to_numpy() + rng.normal(0, 5, n)
        o = tidx[-1] + pd.Timedelta(minutes=30)
        a = edp.MLPLearner(True, 11, "ref")
        a.p = dict(a.p, epochs=2)
        a.fit(Xs, ys, tidx, o)
        pa = a.predict(Xs.iloc[:96])
        b2 = WP4MLPForecaster(True, 11, "wp4")
        b2.p = dict(b2.p, epochs=2)
        b2.fit(Xs, ys, tidx, o)
        pb = b2.predict(Xs.iloc[:96])
        checks.append(("identical seed -> identical predictions (pipeline vs module)",
                       bool(np.allclose(pa, pb, atol=1e-4))))
    return checks


def main() -> int:
    t0 = time.time()
    res = equivalence_checks(run_tf="--no-tf" not in sys.argv)
    for name, ok in res:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
    bad = sum(not ok for _, ok in res)
    print(f"{MODEL_NAME} module equivalence: {len(res) - bad}/{len(res)} passed ({time.time() - t0:.1f}s)")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
