"""
wp4_contracts.py - shared WP4 interface contract (jointly owned, reviewed in Issue 09)

Member:              All four members (integration lead: Ashish Shrestha)
WP4 Role:            Shared data contract for the four WP4 neural modules
Primary Pair:        MLP pair (Ashish + Bishal) and GRU pair (Suraj + Sudip)
Assigned GitHub Issue: ISSUE 09 - Four-module integration into final pipeline
Integration Target:  Energy_Demand_Forecasting_Pipeline.py (v4.0.0), sections P-T
Purpose:             One place that defines the objects passed between the four
                     modules, so they merge as one system rather than four
                     mini-projects. Every constant is read from - and checked
                     against - the integrated pipeline, which stays the source
                     of truth.

Results are generated by the integrated pipeline; this module does not hard-code
model-performance outcomes.
"""
from __future__ import annotations

import importlib.util
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

PIPELINE_FILENAME = "Energy_Demand_Forecasting_Pipeline.py"
EXPECTED_PIPELINE_VERSION = "4.0.0"      # the version that produced the WP4 results

# Contract constants. They duplicate nothing: check_constants() proves they are
# identical to the pipeline's own values before any module is merged.
TIME = "SETTLEMENTDATE"
TARGET = "TOTALDEMAND"
FREQ = "30min"
INTERVALS_PER_DAY = 48
BLOCK = 48
REGIONS = ["NSW1", "QLD1", "VIC1", "SA1", "TAS1", "WA"]
RANDOM_SEED = 20260914

_PIPELINE = None


def load_pipeline(path: str | os.PathLike | None = None):
    """Import the integrated pipeline once (it never runs on import).

    Search order: explicit path -> $WP4_PIPELINE_PATH -> this folder -> parent folder
    -> ../Pipeline/.
    """
    global _PIPELINE
    if _PIPELINE is not None and path is None:
        return _PIPELINE
    here = Path(__file__).resolve().parent
    candidates = [Path(path)] if path else []
    if os.environ.get("WP4_PIPELINE_PATH"):
        candidates.append(Path(os.environ["WP4_PIPELINE_PATH"]))
    candidates += [here / PIPELINE_FILENAME, here.parent / PIPELINE_FILENAME,
                   here.parent / "Pipeline" / PIPELINE_FILENAME]
    for c in candidates:
        if c.is_file():
            spec = importlib.util.spec_from_file_location("energy_pipeline_v4", c)
            mod = importlib.util.module_from_spec(spec)
            sys.modules["energy_pipeline_v4"] = mod
            spec.loader.exec_module(mod)
            _PIPELINE = mod
            return mod
    raise FileNotFoundError(f"{PIPELINE_FILENAME} not found; set WP4_PIPELINE_PATH")


def check_constants(edp=None) -> list[str]:
    """Return a list of mismatches between this contract and the pipeline (empty = OK)."""
    edp = edp or load_pipeline()
    problems = []
    for name, value in (("TIME", TIME), ("TARGET", TARGET), ("FREQ", FREQ),
                        ("INTERVALS_PER_DAY", INTERVALS_PER_DAY), ("BLOCK", BLOCK),
                        ("REGIONS", REGIONS), ("RANDOM_SEED", RANDOM_SEED),
                        ("PIPELINE_VERSION", EXPECTED_PIPELINE_VERSION)):
        if getattr(edp, name) != value:
            problems.append(f"{name}: contract={value!r} pipeline={getattr(edp, name)!r}")
    return problems


# ---------------------------------------------------------------------------
# Shared objects
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ModelInputContract:
    """What a model is allowed to read. Feature order is part of the contract."""
    model_name: str
    feature_set_label: str
    feature_names: tuple
    target: str = TARGET
    frequency: str = FREQ
    requires_tensorflow: bool = False
    excluded_features: tuple = ()

    def validate_frame(self, X: pd.DataFrame) -> None:
        missing = [f for f in self.feature_names if f not in X.columns]
        if missing:
            raise ValueError(f"{self.model_name}: missing features {missing[:5]}")
        leaked = [f for f in self.excluded_features if f in X.columns]
        if leaked:
            raise ValueError(f"{self.model_name}: excluded features present {leaked}")
        if self.target in X.columns:
            raise ValueError(f"{self.model_name}: the target column must not be an input")


@dataclass(frozen=True)
class BacktestContext:
    """One region x historical origin, exactly as validation/backtest_origins.csv."""
    region: str
    backtest_year: int
    origin: pd.Timestamp
    horizon_end: pd.Timestamp
    origin_type: str
    used_for_selection: bool

    @classmethod
    def from_origin_row(cls, row) -> "BacktestContext":
        return cls(region=row["region"], backtest_year=int(row["backtest_year"]),
                   origin=pd.Timestamp(row["origin"]), horizon_end=pd.Timestamp(row["end"]),
                   origin_type=row["origin_type"], used_for_selection=bool(row["used_for_selection"]))

    def validate(self) -> None:
        if self.region not in REGIONS:
            raise ValueError(f"unknown region {self.region}")
        if not self.horizon_end > self.origin:
            raise ValueError("horizon must end after the origin")
        if self.origin_type == "LIMITED_HISTORY_BACKTEST" and self.used_for_selection:
            raise ValueError("a limited-history origin can never be used for selection")


@dataclass
class NeuralScalerBundle:
    """Scalers for one neural fit. `fitted_until` records the last row the scalers saw,
    so a reviewer can prove it lies before the origin."""
    feature_scaler: object
    target_scaler: object
    fitted_until: pd.Timestamp | None = None
    fitted_rows: int = 0

    def assert_before(self, origin: pd.Timestamp) -> None:
        if self.fitted_until is not None and not pd.Timestamp(self.fitted_until) < pd.Timestamp(origin):
            raise AssertionError(f"scalers saw data at {self.fitted_until}, not before origin {origin}")

    def to_dict(self) -> dict:
        return {"feature_scaler": self.feature_scaler.to_dict(),
                "target_scaler": self.target_scaler.to_dict(),
                "fitted_until": str(self.fitted_until), "fitted_rows": self.fitted_rows}


@dataclass
class SequenceBatch:
    """GRU arrays for a set of day-block starts (encoder / known-future decoder / target)."""
    encoder: np.ndarray        # (n, lookback, channels)
    decoder: np.ndarray        # (n, 48, decoder_features)
    target: np.ndarray         # (n, 48)
    starts: np.ndarray         # block start positions
    lookback: int
    origin_pos: int

    def validate(self) -> None:
        n = len(self.starts)
        if not (self.encoder.shape[0] == self.decoder.shape[0] == self.target.shape[0] == n):
            raise ValueError("encoder/decoder/target/starts disagree on sample count")
        if self.encoder.shape[1] != self.lookback or self.decoder.shape[1] != BLOCK or self.target.shape[1] != BLOCK:
            raise ValueError("sequence shapes break the contract")
        if n and int(self.starts.max()) + BLOCK > self.origin_pos:
            raise AssertionError("a training target reaches the forecast origin")
        if n and int(self.starts.min()) - self.lookback < 0:
            raise AssertionError("an encoder window starts before the data")


TRAINING_HISTORY_COLUMNS = ["phase", "epoch", "loss", "val_loss", "learning_rate"]


@dataclass
class TrainingHistory:
    """Per-epoch record, same columns as metrics/neural_training_history.csv."""
    region: str
    model: str
    origin: pd.Timestamp
    frame: pd.DataFrame
    best_epoch: int | None = None

    def validate(self) -> None:
        missing = [c for c in TRAINING_HISTORY_COLUMNS if c not in self.frame.columns]
        if missing:
            raise ValueError(f"training history missing {missing}")

    def to_frame(self) -> pd.DataFrame:
        return self.frame.assign(region=self.region, model=self.model, backtest_origin=self.origin)


@dataclass
class ForecastResult:
    """What every model returns to the backtest engine (a typed view of pipeline.Run)."""
    region: str
    model: str
    origin: pd.Timestamp
    status: str
    forecast: pd.Series | None
    detail: str = ""
    fit_seconds: float = float("nan")
    predict_seconds: float = float("nan")
    filled_cells: int = 0
    history: TrainingHistory | None = None
    extra: dict = field(default_factory=dict)

    @classmethod
    def from_run(cls, run, region: str, origin: pd.Timestamp) -> "ForecastResult":
        hist = None
        if getattr(run, "history", None) is not None and len(run.history):
            hist = TrainingHistory(region, run.name, pd.Timestamp(origin), run.history,
                                   run.extra.get("best_epoch"))
        return cls(region=region, model=run.name, origin=pd.Timestamp(origin), status=run.status,
                   forecast=run.forecast, detail=run.detail, fit_seconds=run.fit_seconds,
                   predict_seconds=run.predict_seconds, filled_cells=run.filled_cells,
                   history=hist, extra=dict(run.extra))

    @property
    def ok(self) -> bool:
        return self.status in ("MODEL_READY", "MODEL_READY_WITH_WARNING")

    def validate(self, horizon_intervals: int | None = None) -> None:
        if self.ok and self.forecast is None:
            raise ValueError("a successful run must carry a forecast")
        if self.ok and horizon_intervals is not None and len(self.forecast) != horizon_intervals:
            raise ValueError("forecast length does not cover the full horizon")
        if self.ok and not np.isfinite(self.forecast.to_numpy(dtype=float)).all():
            raise ValueError("forecast contains non-finite values")


@dataclass
class MetricResult:
    """Metrics for one region/model/scope, computed ONLY by pipeline.metrics()."""
    region: str
    model: str
    scope: str
    values: dict

    @classmethod
    def compute(cls, region: str, model: str, scope: str, actual, forecast, edp=None) -> "MetricResult":
        edp = edp or load_pipeline()
        return cls(region, model, scope, edp.metrics(np.asarray(actual, float), np.asarray(forecast, float)))


def self_test() -> int:
    edp = load_pipeline()
    problems = check_constants(edp)
    for p in problems:
        print("  [FAIL]", p)
    ctx = BacktestContext("SA1", 2025, pd.Timestamp("2025-09-01"), pd.Timestamp("2025-12-31 23:30"),
                          "FULL_HISTORY_BACKTEST", True)
    ctx.validate()
    m = MetricResult.compute("SA1", "demo", "full", [100, 200], [110, 190], edp)
    ok = not problems and abs(m.values["MAE"] - 10.0) < 1e-12
    print(f"wp4_contracts self-test: {'PASS' if ok else 'FAIL'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(self_test())
