"""
WP4_Sudip_GRU_Training_Provenance.py

Member:              Sudip Lamichhane
WP4 Role:            GRU training controls, temporal information boundaries and provenance
Primary Pair:        GRU pair - Suraj Raut (sequence / recursive data path) + Sudip Lamichhane (training / provenance)
Assigned GitHub Issue: ISSUE 05 - GRU training and provenance safeguards
                     (also leads ISSUE 08 leakage / information-boundary review)
Integration Target:  Energy_Demand_Forecasting_Pipeline.py v4.0.0
                     Section S (_build_gru and the training half of run_gru()),
                     Section P (_keras_callbacks, _best_epoch, scalers) and the
                     weather/leakage evidence written to validation/leakage_audit.csv.
Purpose:             Own how the GRU is trained and what it is allowed to know:
                     architecture, TensorFlow controls (Adam, Huber, EarlyStopping,
                     ReduceLROnPlateau, LR-path replay for the refit), deterministic
                     seeds, target/decoder scaling on training rows only, the 8-week
                     validation period, weather/context provenance, information-
                     boundary validation, convergence/failure capture and the
                     learning-history output.

Provenance: role-aligned WP4 collaboration artefact prepared from the team's
integrated implementation for genuine branch-based review and merging. The
integrated pipeline v4.0.0 produced the WP4 results and remains the source of truth.

Results are generated by the integrated pipeline; this module does not hard-code
model-performance outcomes.
"""
from __future__ import annotations

import copy
import sys
import traceback
from datetime import datetime

import numpy as np
import pandas as pd

from wp4_contracts import (BLOCK, NeuralScalerBundle, SequenceBatch, TrainingHistory,
                           check_constants, load_pipeline)

edp = load_pipeline()


# ---------------------------------------------------------------------------
# 1. Configuration and architecture
# ---------------------------------------------------------------------------

def gru_parameters(quick: bool = False) -> dict:
    return copy.deepcopy(edp.GRU_PARAMETERS["quick" if quick else "full"])


def build_gru_network(tf, lookback: int, n_encoder: int, n_decoder: int, p: dict):
    """Encoder GRU over the lookback window -> dropout -> repeated for the 48 steps ->
    concatenated with each step's known-future features -> Dense(ReLU) -> Dense(1).

    Plain GRU settings (tanh/sigmoid, no recurrent_dropout) keep the cuDNN kernel
    eligible on a GPU; dropout is applied as separate layers."""
    L = tf.keras.layers
    enc_in = tf.keras.Input(shape=(lookback, n_encoder), name="history_sequence")
    dec_in = tf.keras.Input(shape=(BLOCK, n_decoder), name="known_future_block")
    ctx = L.GRU(p["gru_units"], name="gru_encoder")(enc_in)
    ctx = L.Dropout(p["dropout"])(ctx)
    rep = L.RepeatVector(BLOCK)(ctx)
    h = L.Concatenate(axis=-1)([rep, dec_in])
    h = L.Dense(p["dense_units"], activation="relu", name="per_step_dense")(h)
    h = L.Dropout(p["dropout"])(h)
    out = L.Dense(1, activation="linear", name="demand_scaled")(h)
    out = L.Reshape((BLOCK,))(out)
    net = tf.keras.Model([enc_in, dec_in], out, name="GRU_day_block_forecaster")
    net.compile(optimizer=tf.keras.optimizers.Adam(p["learning_rate"]),
                loss=tf.keras.losses.Huber(delta=edp.HUBER_DELTA), metrics=["mae"])
    return net


# ---------------------------------------------------------------------------
# 2. Validation period and scaling (information boundary)
# ---------------------------------------------------------------------------

def split_train_validation(starts: np.ndarray, origin_pos: int) -> tuple[np.ndarray, np.ndarray]:
    """Validation = sequences whose block starts in the last NEURAL_VALIDATION_DAYS before
    the origin; training sequences must END before that block (no straddling). If the
    history is too short the last 10% of sequences is used instead (pipeline rule)."""
    val_pos = origin_pos - edp.NEURAL_VALIDATION_DAYS * edp.INTERVALS_PER_DAY
    tr = starts[starts + BLOCK <= val_pos]
    va = starts[starts >= val_pos]
    if len(va) < 10 or len(tr) < 100:
        cut = int(len(starts) * 0.9)
        tr, va = starts[:cut], starts[cut:]
    if len(va) and len(tr):
        assert int(tr.max()) < int(va.min()), "validation sequences must follow training sequences"
    assert (va + BLOCK <= origin_pos).all(), "validation reaches the forecast horizon"
    return tr, va


def fit_gru_scalers(y: np.ndarray, D: np.ndarray, limit: int, index: pd.DatetimeIndex,
                    decoder_features: list) -> NeuralScalerBundle:
    """Target scaler on demand before `limit`; decoder scaler on known-future rows before
    `limit`. `limit` is the end of the training sequences (early-stopping fit) or the
    origin (refit) - never beyond it."""
    ts = edp.TargetScaler().fit(y[:limit])
    ds = edp.ColumnScaler(decoder_features).fit(D[:limit])
    return NeuralScalerBundle(ds, ts, fitted_until=index[limit - 1], fitted_rows=int(limit))


# ---------------------------------------------------------------------------
# 3. Training controls
# ---------------------------------------------------------------------------

def train_gru(tf, train: SequenceBatch, val: SequenceBatch, p: dict, seed: int, label: str):
    """Early-stopped fit. Returns (net, history_frame, best_epoch, lr_path)."""
    train.validate()
    val.validate()
    tf.keras.backend.clear_session()
    edp.set_global_seeds(seed)
    net = build_gru_network(tf, train.lookback, train.encoder.shape[2], train.decoder.shape[2], p)
    cbs, rec = edp._keras_callbacks(tf, p, label, with_validation=True)
    net.fit([train.encoder, train.decoder], train.target,
            validation_data=([val.encoder, val.decoder], val.target),
            epochs=p["epochs"], batch_size=p["batch_size"], shuffle=True, verbose=0, callbacks=cbs)
    edp.check_cancel()
    best, lr_path = edp._best_epoch(rec)
    return net, edp._history_frame(rec, "early_stopping_fit"), best, lr_path


def refit_gru(tf, full: SequenceBatch, p: dict, seed: int, best_epoch: int, lr_path: list, label: str):
    """Refit on every pre-origin sequence for the early-stopped epoch count, replaying the
    learning-rate path (no validation data exists at this stage)."""
    full.validate()
    tf.keras.backend.clear_session()
    edp.set_global_seeds(seed)
    net = build_gru_network(tf, full.lookback, full.encoder.shape[2], full.decoder.shape[2], p)
    cbs, rec = edp._keras_callbacks(tf, p, label + " refit", with_validation=False, lr_replay=lr_path)
    net.fit([full.encoder, full.decoder], full.target, epochs=max(1, best_epoch),
            batch_size=p["batch_size"], shuffle=True, verbose=0, callbacks=cbs)
    edp.check_cancel()
    return net, edp._history_frame(rec, "refit_full_history")


def learning_history(region: str, model: str, origin, frames: list, best_epoch) -> TrainingHistory:
    th = TrainingHistory(region, model, pd.Timestamp(origin), pd.concat(frames, ignore_index=True), best_epoch)
    th.validate()
    return th


def convergence_flags(history: pd.DataFrame, epoch_limit: int) -> dict:
    """Declared diagnostics for the report (not used for selection)."""
    e = history[history["phase"] == "early_stopping_fit"]
    if e.empty:
        return {"status": "NO_HISTORY"}
    best = int(e.loc[e["val_loss"].idxmin(), "epoch"])
    return {"epochs_run": int(e["epoch"].max()), "best_epoch": best,
            "hit_epoch_limit": bool(best == int(e["epoch"].max()) == epoch_limit),
            "lr_reduced": bool(e["learning_rate"].min() < e["learning_rate"].max())}


def capture_failure(region: str, model: str, origin, stage: str, exc: BaseException) -> dict:
    """Row in the model_failures.csv format - a failure is recorded, never hidden."""
    return {"region": region, "model": model, "backtest_origin": origin, "stage": stage,
            "error_message": f"{type(exc).__name__}: {exc}"[:2000], "exception_type": type(exc).__name__,
            "traceback_tail": "".join(traceback.format_exception(type(exc), exc, exc.__traceback__))[-1500:],
            "recorded_at": datetime.now().isoformat(timespec="seconds"), "status": "MODEL_FAILED"}


# ---------------------------------------------------------------------------
# 4. Weather / context provenance and information-boundary validation
# ---------------------------------------------------------------------------

def validate_weather_provenance(panel, mode: str = "historical_backtest") -> dict:
    """Every horizon row must carry origin-safe climatology, never realised weather."""
    k = panel.known
    expected = "BACKTEST_CLIMATOLOGY" if mode == "historical_backtest" else "PRODUCTION_CLIMATOLOGY"
    src = sorted(set(k.get("weather_feature_source", pd.Series(dtype=str)).astype(str)))
    info = pd.to_datetime(k.get("weather_information_origin", pd.Series(dtype="datetime64[ns]")))
    origin = panel.index[panel.origin_pos]
    return {"sources": src, "only_expected_source": src == [expected],
            "information_origin_is_forecast_origin": bool(len(info) and (info == origin).all())}


def validate_information_boundary(panel, maps, scalers: NeuralScalerBundle | None = None) -> dict:
    origin = panel.index[panel.origin_pos]
    res = {
        "history_ends_before_origin": bool(maps.history_end is not None and maps.history_end < origin),
        "target_hidden_from_horizon_rows": not any(c in panel.known.columns for c in edp.HORIZON_HIDDEN_COLUMNS),
        "no_actual_demand_after_origin": bool(np.isnan(panel.y[panel.origin_pos:]).all()),
    }
    if scalers is not None:
        try:
            scalers.assert_before(origin)
            res["scalers_fitted_before_origin"] = True
        except AssertionError:
            res["scalers_fitted_before_origin"] = False
    res["PASS"] = all(v for v in res.values())
    return res


# ---------------------------------------------------------------------------
# 5. Equivalence checks
# ---------------------------------------------------------------------------

def equivalence_checks() -> list[tuple[str, bool]]:
    checks = [("contract constants match pipeline", not check_constants(edp)),
              ("full GRU parameters equal pipeline", gru_parameters() == edp.GRU_PARAMETERS["full"]),
              ("quick GRU parameters equal pipeline", gru_parameters(True) == edp.GRU_PARAMETERS["quick"])]
    starts = np.arange(700, 30000 - BLOCK + 1, 12)
    tr, va = split_train_validation(starts, 30000)
    val_pos = 30000 - edp.NEURAL_VALIDATION_DAYS * 48
    checks.append(("validation = last 56 days, no straddling sequence",
                   bool((tr + BLOCK <= val_pos).all() and (va >= val_pos).all())))
    idx = pd.date_range("2024-01-01", periods=5000, freq="30min")
    y = np.random.default_rng(2).normal(1000, 50, 5000)
    y[4000:] = np.nan
    b = fit_gru_scalers(y, np.random.default_rng(3).normal(size=(5000, 3)), 3500, idx, ["a", "b", "c"])
    checks.append(("scalers fitted before the limit only", b.fitted_until == idx[3499] and b.fitted_rows == 3500))
    # provenance on a synthetic panel
    gidx = pd.date_range("2025-01-01", periods=200, freq="30min")
    known = pd.DataFrame({"weather_feature_source": "BACKTEST_CLIMATOLOGY",
                          "weather_information_origin": gidx[100]}, index=gidx[100:])
    panel = edp.Panel(index=gidx, y=np.r_[np.ones(100), np.full(100, np.nan)], actual=np.ones(200),
                      origin_pos=100, grid_pos=np.arange(100, 200), known=known,
                      train_rows=pd.DataFrame(), train_pos=np.arange(100))
    maps = edp.OriginMaps(gidx[100], {}, None, None, None, 100, gidx[99], "2025")
    checks.append(("weather provenance check passes on climatology rows",
                   validate_weather_provenance(panel)["only_expected_source"]))
    checks.append(("information boundary check passes", validate_information_boundary(panel, maps)["PASS"]))
    bad = edp.Panel(index=gidx, y=np.ones(200), actual=np.ones(200), origin_pos=100,
                    grid_pos=np.arange(100, 200), known=known.assign(TOTALDEMAND=1.0),
                    train_rows=pd.DataFrame(), train_pos=np.arange(100))
    checks.append(("information boundary check catches leaked target/actuals",
                   not validate_information_boundary(bad, maps)["PASS"]))
    if edp.tf_status()["available"]:
        tf = edp.get_tf()
        for mode, look in (("full", 336), ("full", 672), ("quick", 336)):
            p = edp.GRU_PARAMETERS[mode]
            same = (build_gru_network(tf, look, 6, 41, p).count_params()
                    == edp._build_gru(tf, look, 6, 41, p).count_params())
            checks.append((f"{mode} architecture parameter count equals pipeline (L={look})", same))
        # identical seeds -> identical trained weights (module vs pipeline building blocks)
        p = dict(gru_parameters(True), gru_units=8, dense_units=8, epochs=2, batch_size=32)
        rng = np.random.default_rng(5)
        mk = lambda n, s0: SequenceBatch(rng.normal(size=(n, 48, 2)).astype(np.float32),
                                         rng.normal(size=(n, 48, 3)).astype(np.float32),
                                         rng.normal(size=(n, 48)).astype(np.float32),
                                         np.arange(s0, s0 + n), 48, 10_000)
        tr_b, va_b = mk(64, 100), mk(16, 400)
        net1, _, best1, _ = train_gru(tf, tr_b, va_b, p, 17, "module")
        tf.keras.backend.clear_session()
        edp.set_global_seeds(17)
        net2 = edp._build_gru(tf, 48, 2, 3, p)
        cbs, _ = edp._keras_callbacks(tf, p, "pipeline", with_validation=True)
        net2.fit([tr_b.encoder, tr_b.decoder], tr_b.target, validation_data=([va_b.encoder, va_b.decoder], va_b.target),
                 epochs=p["epochs"], batch_size=p["batch_size"], shuffle=True, verbose=0, callbacks=cbs)
        w_same = all(np.allclose(a, b, atol=1e-5) for a, b in zip(net1.get_weights(), net2.get_weights()))
        checks.append(("identical seed -> identical trained weights (module vs pipeline)", w_same))
    return checks


def main() -> int:
    res = equivalence_checks()
    for name, ok in res:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
    bad = sum(not ok for _, ok in res)
    print(f"GRU training/provenance equivalence: {len(res) - bad}/{len(res)} passed")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
