"""
WP4_Suraj_GRU_Sequence_Engine.py

Member:              Suraj Raut
WP4 Role:            GRU sequence preparation and recursive four-month engine
Primary Pair:        GRU pair - Suraj Raut (sequence / recursive data path) + Sudip Lamichhane (training / provenance)
Assigned GitHub Issue: ISSUE 04 - GRU sequence and recursive engine
Integration Target:  Energy_Demand_Forecasting_Pipeline.py v4.0.0, Section R
                     (gru_training_starts, build_gru_arrays, _nan_count_windows,
                     GRU_DECODER_FEATURES / GRU_ENCODER_CALENDAR) and the data path
                     inside run_gru(): known-future matrices, encoder windows and the
                     day-block recursion.
Purpose:             Own the temporal data path of the GRU: 336-step (and optional
                     672-step sensitivity) lookback windows, sequence/target alignment,
                     the chronological origin boundary, recursive window updates with
                     explicit actual-vs-predicted provenance, known-future calendar
                     inputs, and the checks that prove no horizon actual can enter an
                     encoder window.

Provenance: role-aligned WP4 collaboration artefact prepared from the team's
integrated implementation for genuine branch-based review and merging. The
integrated pipeline v4.0.0 produced the WP4 results and remains the source of truth.

Results are generated by the integrated pipeline; this module does not hard-code
model-performance outcomes.
"""
from __future__ import annotations

import sys
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from wp4_contracts import BLOCK, SequenceBatch, check_constants, load_pipeline

edp = load_pipeline()


# ---------------------------------------------------------------------------
# 1. Sequence specification
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SequenceSpec:
    """Lookback 336 = 7 days (primary GRU). 672 = 14 days is SENSITIVITY_ONLY (GRU_L672)."""
    lookback: int = edp.GRU_LOOKBACK
    stride: int = edp.GRU_PARAMETERS["full"]["train_stride"]
    model_name: str = "GRU"

    @classmethod
    def primary(cls, quick: bool = False) -> "SequenceSpec":
        return cls(edp.GRU_LOOKBACK, edp.GRU_PARAMETERS["quick" if quick else "full"]["train_stride"], "GRU")

    @classmethod
    def sensitivity(cls, quick: bool = False) -> "SequenceSpec":
        return cls(edp.GRU_SENSITIVITY_LOOKBACK, edp.GRU_PARAMETERS["quick" if quick else "full"]["train_stride"],
                   edp.SENSITIVITY_MODEL)

    @property
    def competes_in_selection(self) -> bool:
        return self.model_name in edp.MODEL_REGISTRY


ENCODER_CHANNELS = ["demand_scaled"] + list(edp.GRU_ENCODER_CALENDAR)
DECODER_FEATURES = list(edp.GRU_DECODER_FEATURES)


# ---------------------------------------------------------------------------
# 2. Training sequences - alignment and origin boundary
# ---------------------------------------------------------------------------

def _nan_count(bad: np.ndarray, starts: np.ndarray, lo: int, hi: int) -> np.ndarray:
    c = np.concatenate([[0], np.cumsum(bad.astype(np.int64))])
    return c[starts + hi] - c[starts + lo]


def training_starts(y: np.ndarray, origin_pos: int, spec: SequenceSpec) -> np.ndarray:
    """Block starts s whose encoder window [s-L, s) and 48 targets [s, s+48) are complete
    and lie entirely BEFORE the origin. Windows touching a data gap are skipped."""
    first = max(spec.lookback, edp.WARMUP_INTERVALS)
    last = origin_pos - BLOCK
    if last < first:
        return np.array([], dtype=np.int64)
    starts = np.arange(first, last + 1, spec.stride, dtype=np.int64)
    ok = _nan_count(~np.isfinite(y), starts, -spec.lookback, BLOCK) == 0
    starts = starts[ok]
    if len(starts):
        assert int(starts.max()) + BLOCK <= origin_pos, "training target reaches the origin"
    return starts


def build_sequence_batch(y_scaled: np.ndarray, encoder_calendar: np.ndarray, decoder_scaled: np.ndarray,
                         starts: np.ndarray, spec: SequenceSpec, origin_pos: int) -> SequenceBatch:
    """Encoder (n, L, 1+calendar), decoder (n, 48, D) and target (n, 48) for each start.
    The encoder's last step is position s-1; the target's first step is position s."""
    from numpy.lib.stride_tricks import sliding_window_view
    enc = np.column_stack([y_scaled, encoder_calendar]).astype(np.float32)
    enc_w = sliding_window_view(enc, spec.lookback, axis=0)
    dec_w = sliding_window_view(decoder_scaled, BLOCK, axis=0)
    tgt_w = sliding_window_view(y_scaled, BLOCK)
    batch = SequenceBatch(
        encoder=np.ascontiguousarray(enc_w[starts - spec.lookback].transpose(0, 2, 1)),
        decoder=np.ascontiguousarray(dec_w[starts].transpose(0, 2, 1)),
        target=np.ascontiguousarray(tgt_w[starts]).astype(np.float32),
        starts=starts, lookback=spec.lookback, origin_pos=origin_pos)
    batch.validate()
    return batch


# ---------------------------------------------------------------------------
# 3. Known-future inputs (calendar / holidays / profiles / weather policy)
# ---------------------------------------------------------------------------

def known_future_matrices(panel, rd, maps) -> tuple[np.ndarray, np.ndarray]:
    """Decoder matrix D (n x 41 known-future features) and encoder calendar E (n x 5)
    for every panel position. History rows carry observed calendar/weather; horizon
    rows carry panel.known, i.e. calendar + origin-safe climatology weather. The target
    and demand-derived columns are removed before anything is read."""
    n, opos = len(panel.index), panel.origin_pos
    hidden = [c for c in edp.HORIZON_HIDDEN_COLUMNS if c in rd.base.columns]
    hist_rows = rd.base.reindex(panel.index[:opos]).drop(columns=hidden, errors="ignore")
    known_all = pd.concat([hist_rows, panel.known], axis=0, sort=False).reindex(panel.index)
    assert edp.TARGET not in known_all.columns, "target visible in known-future frame"
    D = edp.design_matrix(known_all, np.arange(n), panel.y, DECODER_FEATURES, maps).to_numpy(dtype=float)
    E = known_all.reindex(columns=edp.GRU_ENCODER_CALENDAR).to_numpy(dtype=float)
    E = np.where(np.isfinite(E), E, 0.0).astype(np.float32)
    return D, E


# ---------------------------------------------------------------------------
# 4. Recursive day-block state with provenance
# ---------------------------------------------------------------------------

@dataclass
class RecursiveSequenceState:
    """Demand history used by the recursion. Positions >= origin are NaN until this
    model predicts them; `predicted` marks which values are the model's own output."""
    y: np.ndarray
    origin_pos: int
    lookback: int
    predicted: np.ndarray = field(init=False)
    log: list = field(default_factory=list)

    def __post_init__(self):
        self.y = np.asarray(self.y, dtype=float).copy()
        self.y[self.origin_pos:] = np.nan            # nothing at/after the origin is known
        self.predicted = np.zeros(len(self.y), bool)

    def encoder_window(self, block_start: int) -> tuple[np.ndarray, dict]:
        lo, hi = block_start - self.lookback, block_start
        win = self.y[lo:hi].copy()
        pos = np.arange(lo, hi)
        actual_steps = int(np.sum(pos < self.origin_pos))
        predicted_steps = int(np.sum(pos >= self.origin_pos))
        if predicted_steps and not self.predicted[pos[pos >= self.origin_pos]].all():
            raise AssertionError("encoder window reads a horizon value that was not predicted")
        filled = 0
        if not np.isfinite(win).all():               # only pre-origin data gaps
            filled = int((~np.isfinite(win)).sum())
            win = pd.Series(win).interpolate(limit_direction="both").to_numpy()
        info = {"block_start": block_start, "actual_steps": actual_steps,
                "predicted_steps": predicted_steps, "gap_filled_steps": filled}
        self.log.append(info)
        return win, info

    def update(self, block_positions: np.ndarray, prediction_mw: np.ndarray) -> None:
        if (np.asarray(block_positions) < self.origin_pos).any():
            raise AssertionError("recursion may only write positions at or after the origin")
        self.y[block_positions] = prediction_mw
        self.predicted[block_positions] = True

    def provenance(self) -> dict:
        return {"blocks": len(self.log),
                "actual_encoder_steps": sum(i["actual_steps"] for i in self.log),
                "predicted_encoder_steps": sum(i["predicted_steps"] for i in self.log),
                "gap_filled_steps": sum(i["gap_filled_steps"] for i in self.log)}


def recursive_forecast(predict_block, state: RecursiveSequenceState, grid_pos: np.ndarray,
                       E: np.ndarray, D_scaled: np.ndarray, target_scaler) -> np.ndarray:
    """Four-month forecast in 48-interval day blocks (same loop as pipeline.run_gru).

    predict_block(encoder[1, L, C], decoder[1, 48, D]) -> 48 scaled values.
    Supplied by the training module (Sudip) - this engine never sees a network."""
    preds = np.full(len(grid_pos), np.nan)
    L = state.lookback
    for b in range(0, len(grid_pos), BLOCK):
        edp.check_cancel()
        blk = grid_pos[b:b + BLOCK]
        s = int(blk[0])
        win, _ = state.encoder_window(s)
        enc = np.column_stack([target_scaler.transform(win), E[s - L:s]])[None].astype(np.float32)
        rows = D_scaled[s:s + BLOCK]
        if len(rows) < BLOCK:
            rows = np.vstack([rows, np.repeat(rows[-1:], BLOCK - len(rows), axis=0)])
        z = np.asarray(predict_block(enc, rows[None].astype(np.float32))).reshape(-1)[:len(blk)]
        yhat = target_scaler.inverse(z)
        state.update(blk, yhat)
        preds[b:b + len(blk)] = yhat
    return preds


# ---------------------------------------------------------------------------
# 5. Equivalence and leakage checks
# ---------------------------------------------------------------------------

def equivalence_checks() -> list[tuple[str, bool]]:
    checks = [("contract constants match pipeline", not check_constants(edp)),
              ("decoder features equal pipeline (41, no demand-derived)",
               DECODER_FEATURES == list(edp.GRU_DECODER_FEATURES) and not set(DECODER_FEATURES) & edp.DEMAND_FEATURES),
              ("primary lookback 336 / sensitivity 672",
               SequenceSpec.primary().lookback == 336 and SequenceSpec.sensitivity().lookback == 672),
              ("GRU_L672 is sensitivity-only", not SequenceSpec.sensitivity().competes_in_selection)]
    y = np.arange(9000, dtype=float)
    opos = 8000
    y[opos:] = np.nan
    y[3000] = np.nan
    for spec in (SequenceSpec.primary(), SequenceSpec.sensitivity(), SequenceSpec.primary(quick=True)):
        a = training_starts(y, opos, spec)
        b = edp.gru_training_starts(y, opos, spec.lookback, spec.stride)
        checks.append((f"training starts identical to pipeline (L={spec.lookback}, stride={spec.stride})",
                       np.array_equal(a, b)))
        checks.append((f"windows containing the gap are skipped (L={spec.lookback})",
                       not any(s - spec.lookback <= 3000 < s + BLOCK for s in a)))
    spec = SequenceSpec.primary()
    starts = training_starts(y, opos, spec)[:20]
    ys = np.nan_to_num(y)
    Ecal = np.zeros((len(y), len(edp.GRU_ENCODER_CALENDAR)), np.float32)
    Dm = np.random.default_rng(1).normal(size=(len(y), 3)).astype(np.float32)
    batch = build_sequence_batch(ys, Ecal, Dm, starts, spec, opos)
    ref = edp.build_gru_arrays(ys, Ecal, Dm, starts, spec.lookback)
    checks.append(("sequence arrays identical to pipeline",
                   all(np.array_equal(p, q) for p, q in zip((batch.encoder, batch.decoder, batch.target), ref))))
    checks.append(("encoder ends at s-1, target starts at s",
                   bool(np.allclose(batch.encoder[:, -1, 0], starts - 1) and np.allclose(batch.target[:, 0], starts))))
    # recursion never exposes a horizon actual: plant a sentinel in the actuals
    actual = np.full(3000, 500.0)
    actual[2000:] = 1e9                        # would be obvious if it leaked
    st = RecursiveSequenceState(actual, 2000, 336)
    grid = np.arange(2000, 2000 + 5 * BLOCK)

    class Identity:
        def transform(self, v):
            return np.asarray(v, float)

        def inverse(self, z):
            return np.asarray(z, float)
    seen = []

    def fake_block(enc, dec):
        seen.append(float(np.max(enc[0, :, 0])))
        return np.full(BLOCK, 510.0)
    recursive_forecast(fake_block, st, grid, np.zeros((3000, 5)), np.zeros((3000, 2)), Identity())
    prov = st.provenance()
    checks.append(("no horizon actual ever enters an encoder window", max(seen) < 1e6))
    checks.append(("provenance: block 1 all actual, later blocks include predictions",
                   st.log[0]["predicted_steps"] == 0 and st.log[1]["predicted_steps"] == BLOCK
                   and prov["actual_encoder_steps"] + prov["predicted_encoder_steps"] == 5 * 336))
    return checks


def main() -> int:
    res = equivalence_checks()
    for name, ok in res:
        print(f"  [{'PASS' if ok else 'FAIL'}] {name}")
    bad = sum(not ok for _, ok in res)
    print(f"GRU sequence engine equivalence: {len(res) - bad}/{len(res)} passed")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
